name: Update KDS Roadmap project statuses on Release

on:
  release:
    types: [published]

jobs:
  update-issues-statuses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.LE_BOT_APP_ID }}
          private_key: ${{ secrets.LE_BOT_PRIVATE_KEY }}

      - name: Update Issues statuses
        uses: actions/github-script@v7
        env:
          KDS_ROADMAP_PROJECT_NUMBER: ${{ secrets.KDS_ROADMAP_PROJECT_NUMBER }}
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const { updateReleasedItemsStatuses } = require('./.github/githubUtils.js');
            const projectNumber = process.env.KDS_ROADMAP_PROJECT_NUMBER;
            updateReleasedItemsStatuses({context, github, projectNumber});